version: "3"
services:
  grader:
    build: .
    security_opt:
      - seccomp:unconfined
    links:
      - db
    ports:
      - 3000:3000
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: db
    volumes:
      - main:/cafe_grader
  db:
    image: mysql:5.7
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - persistent:/var/lib/mysql
volumes:
  main:
  persistent:
