version: "3"
services:
  grader:
    build: .
    security_opt:
      - seccomp:unconfined
    links:
      - db
    ports:
      - 443:3000
    environment:
      MYSQL_ROOT_PASSWORD: p@ssw0rdsupersecret 
      MYSQL_USER: root
      MYSQL_PASSWORD: p@ssw0rdsupersecret
      MYSQL_DATABASE: db
    volumes:
      - main:/cafe_grader
      - ./server.key:/cafe_grader/server.key
      - ./server.crt:/cafe_grader/server.crt
  db:
    image: mysql:5.7
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: p@ssw0rdsupersecret
    volumes:
      - persistent:/var/lib/mysql
volumes:
  main:
  persistent:
