version: "3"
services:
  grader:
    build: ./grader
    security_opt:
      - seccomp:unconfined
    links:
      - db
    ports:
      - 8080:8080
    environment:
      MYSQL_ROOT_PASSWORD: p@ssw0rdsupersecret 
      MYSQL_USER: root
      MYSQL_PASSWORD: p@ssw0rdsupersecret
      MYSQL_DATABASE: db
    volumes:
      - main:/cafe_grader
      - ./ev:/cafe_grader/judge/ev
  db:
    image: mysql:5.7
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: p@ssw0rdsupersecret
    volumes:
      - persistent:/var/lib/mysql
  nginx:
    build: ./nginx
    links:
      - grader
    ports:
      - 80:80
      - 443:443
    volumes:
      - main:/cafe_grader
      - ./cert:/cert:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
volumes:
  main:
  persistent:
