name: Docker Build Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the grader web image
      run: docker build . --file ./grader/Dockerfile --tag grader:$(date +%s)
    - name: Build the NGINX image
      run: docker build . --file ./nginx/Dockerfile --tag nginx:$(date +%s)
